package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// A rendered base in the exact shape the renderers emit: two header comment
// lines, then blank-separated [Section] blocks of Key=Value lines, trailing NL.
const sampleBase = `; Generated by waypointd from the configuration store — do NOT edit.
; Edits are overwritten on the next Apply. Use the override layer instead.

[General]
Callsign=N0CALL
Id=1234567
Duplex=1

[DMR]
Enable=1
ColorCode=1
`

// Property 5 (inertness) + reserialize fidelity: parse then render reproduces the
// base byte-for-byte, and an empty/comment-only fragment set changes nothing.
func TestApplyOverrides_Inert(t *testing.T) {
	if got := parseOverrideDoc(sampleBase).render(); got != sampleBase {
		t.Fatalf("reserialize not byte-identical:\n--- got ---\n%q\n--- want ---\n%q", got, sampleBase)
	}
	for _, frags := range [][]Fragment{
		nil,
		{ParseFragment("00-empty.conf", "")},
		{ParseFragment("00-comments.conf", "; just a comment\n# another\n\n")},
	} {
		got, report := ApplyOverrides("mmdvm", sampleBase, frags)
		if got != sampleBase {
			t.Errorf("frags %v: output changed:\n%q", frags, got)
		}
		if len(report) != 0 {
			t.Errorf("frags %v: expected empty report, got %v", frags, report)
		}
	}
}

// Property 1: the four merge cases, line-preserving.
func TestApplyOverrides_MergeSemantics(t *testing.T) {
	frag := ParseFragment("10-edit.conf", strings.Join([]string{
		"[DMR]",
		"ColorCode=7",      // replace existing key in place
		"EmbeddedLCOnly=1", // add key to existing section
		"Duplex=!unset",    // wrong section on purpose: no [General] key here
		"[FM]",             // add a new section
		"Enable=1",
		"[General]",
		"Duplex=!unset", // delete a rendered key
	}, "\n"))
	got, report := ApplyOverrides("mmdvm", sampleBase, []Fragment{frag})

	want := `; Generated by waypointd from the configuration store — do NOT edit.
; Edits are overwritten on the next Apply. Use the override layer instead.

[General]
Callsign=N0CALL
Id=1234567

[DMR]
Enable=1
ColorCode=7
EmbeddedLCOnly=1

[FM]
Enable=1
`
	if got != want {
		t.Fatalf("merged output:\n--- got ---\n%s\n--- want ---\n%s", got, want)
	}

	// Report: ColorCode changed, EmbeddedLCOnly added, FM.Enable added, General.Duplex unset.
	byKey := map[string]Applied{}
	for _, a := range report {
		byKey[a.Section+"."+a.Key] = a
	}
	if a := byKey["DMR.ColorCode"]; a.Old != "1" || a.New != "7" || a.Added || a.Unset || a.Source != "10-edit.conf" {
		t.Errorf("DMR.ColorCode report wrong: %+v", a)
	}
	if a := byKey["DMR.EmbeddedLCOnly"]; !a.Added || a.New != "1" || a.Old != "" {
		t.Errorf("DMR.EmbeddedLCOnly report wrong: %+v", a)
	}
	if a := byKey["FM.Enable"]; !a.Added || a.New != "1" {
		t.Errorf("FM.Enable report wrong: %+v", a)
	}
	if a := byKey["General.Duplex"]; !a.Unset || a.Old != "1" || a.New != "" {
		t.Errorf("General.Duplex report wrong: %+v", a)
	}
	if len(report) != 4 {
		t.Errorf("expected 4 report records, got %d: %+v", len(report), report)
	}
}

// !unset of a missing key is a no-op; case-insensitive section/key matching.
func TestApplyOverrides_Edges(t *testing.T) {
	// !unset a key that isn't there
	got, report := ApplyOverrides("mmdvm", sampleBase, []Fragment{ParseFragment("10.conf", "[DMR]\nNope=!unset")})
	if got != sampleBase {
		t.Errorf("no-op unset changed output:\n%s", got)
	}
	if len(report) != 0 {
		t.Errorf("no-op unset produced report: %v", report)
	}
	// case-insensitive match: [dmr] colorcode replaces [DMR] ColorCode, keeps spelling
	got, _ = ApplyOverrides("mmdvm", sampleBase, []Fragment{ParseFragment("10.conf", "[dmr]\ncolorcode=9")})
	if !strings.Contains(got, "ColorCode=9") {
		t.Errorf("case-insensitive replace failed, spelling not preserved:\n%s", got)
	}
	if strings.Contains(got, "colorcode=9") {
		t.Errorf("override introduced lowercase key spelling:\n%s", got)
	}
}

// Property 2: precedence — lexically-later fragment wins; later line within a
// fragment wins.
func TestApplyOverrides_Precedence(t *testing.T) {
	a := ParseFragment("10-a.conf", "[DMR]\nColorCode=3")
	b := ParseFragment("50-b.conf", "[DMR]\nColorCode=8")
	got, report := ApplyOverrides("mmdvm", sampleBase, []Fragment{a, b})
	if !strings.Contains(got, "ColorCode=8") {
		t.Errorf("later fragment did not win:\n%s", got)
	}
	if len(report) != 1 || report[0].New != "8" || report[0].Source != "50-b.conf" {
		t.Errorf("report should credit the winning fragment: %+v", report)
	}
	// later line within one fragment wins
	got, _ = ApplyOverrides("mmdvm", sampleBase, []Fragment{ParseFragment("10.conf", "[DMR]\nColorCode=3\nColorCode=6")})
	if !strings.Contains(got, "ColorCode=6") {
		t.Errorf("later line did not win:\n%s", got)
	}
}

// Property 4: update survival — render+merge is idempotent across a re-apply.
func TestApplyOverrides_UpdateSurvival(t *testing.T) {
	frags := []Fragment{
		ParseFragment("10-a.conf", "[DMR]\nColorCode=7\n[FM]\nEnable=1"),
		ParseFragment("20-b.conf", "[General]\nDuplex=!unset\nNewKey=hi"),
	}
	first, r1 := ApplyOverrides("mmdvm", sampleBase, frags)
	second, r2 := ApplyOverrides("mmdvm", sampleBase, frags) // "an update re-renders the same base"
	if first != second {
		t.Fatalf("not idempotent:\n--- first ---\n%s\n--- second ---\n%s", first, second)
	}
	if len(r1) != len(r2) {
		t.Fatalf("report not stable across re-apply: %d vs %d", len(r1), len(r2))
	}
	// And merging the already-merged output with the same fragments is stable too
	// (a stronger idempotence: the effective file is a fixed point).
	third, _ := ApplyOverrides("mmdvm", first, frags)
	if third != first {
		t.Errorf("merge of merged output not a fixed point:\n--- first ---\n%s\n--- third ---\n%s", first, third)
	}
}

// Property 3 (isolation): an override on section A leaves every line outside A
// byte-identical to the pure base.
func TestApplyOverrides_Isolation(t *testing.T) {
	got, _ := ApplyOverrides("mmdvm", sampleBase, []Fragment{ParseFragment("10.conf", "[DMR]\nColorCode=7")})
	// The [General] block must be untouched.
	genBase := section(sampleBase, "General")
	genGot := section(got, "General")
	if genBase != genGot {
		t.Errorf("[General] changed by a [DMR] override:\n--- base ---\n%s\n--- got ---\n%s", genBase, genGot)
	}
}

func TestLoadFragments(t *testing.T) {
	dir := t.TempDir()
	// Deliberately out of lexical order on disk; LoadFragments must sort.
	write(t, dir, "50-second.conf", "[DMR]\nColorCode=8")
	write(t, dir, "10-first.conf", "[DMR]\nColorCode=3")
	write(t, dir, "notaconf.txt", "[DMR]\nColorCode=99") // ignored
	frags, warnings, err := LoadFragments(dir)
	if err != nil {
		t.Fatal(err)
	}
	if len(warnings) != 0 {
		t.Errorf("unexpected warnings: %v", warnings)
	}
	if len(frags) != 2 || frags[0].Name != "10-first.conf" || frags[1].Name != "50-second.conf" {
		t.Fatalf("fragments not sorted/filtered: %+v", frags)
	}
	got, _ := ApplyOverrides("mmdvm", sampleBase, frags)
	if !strings.Contains(got, "ColorCode=8") {
		t.Errorf("lexically-last fragment did not win after LoadFragments:\n%s", got)
	}

	// Missing directory is inert, not an error.
	frags, _, err = LoadFragments(filepath.Join(dir, "nope"))
	if err != nil || frags != nil {
		t.Errorf("missing dir should be inert: frags=%v err=%v", frags, err)
	}
}

func TestParseFragment_Warnings(t *testing.T) {
	f := ParseFragment("bad.conf", "[DMR]\nthislinehasnoequals\nColorCode=5\n=novalueforkey")
	if len(f.Ops) != 1 || f.Ops[0].key != "ColorCode" {
		t.Errorf("expected 1 valid op, got %+v", f.Ops)
	}
	if len(f.Warnings) != 2 {
		t.Errorf("expected 2 warnings (malformed + empty key), got %v", f.Warnings)
	}
}

// Isolation + update-survival against a REAL renderer output, not just the sample.
func TestApplyOverrides_RealRender(t *testing.T) {
	m := fixture()
	base := m.RenderMMDVM()
	if got := parseOverrideDoc(base).render(); got != base {
		t.Fatalf("real render does not reserialize byte-identically")
	}
	frags := []Fragment{ParseFragment("10.conf", "[General]\nTimeout=600\n[Custom]\nFoo=bar")}
	first, report := ApplyOverrides("mmdvm", base, frags)
	second, _ := ApplyOverrides("mmdvm", base, frags)
	if first != second {
		t.Fatalf("real-render merge not idempotent")
	}
	if !strings.Contains(first, "Timeout=600") || !strings.Contains(first, "[Custom]\nFoo=bar") {
		t.Errorf("real-render merge missing edits:\n%s", first)
	}
	// Timeout changed + Custom.Foo added = 2 records.
	if len(report) != 2 {
		t.Errorf("expected 2 report records on real render, got %d: %+v", len(report), report)
	}
}

// End-to-end through the render pipeline: a fragment on disk under
// <OverridesDir>/mmdvm.d/ is merged into the written MMDVM-Host.ini, reported by
// Overrides(), and re-applying (an "update") produces byte-identical files.
func TestWriteFiles_Overrides(t *testing.T) {
	m := fixture()
	dir := t.TempDir()
	etc := t.TempDir()
	if err := os.MkdirAll(filepath.Join(dir, "mmdvm.d"), 0o755); err != nil {
		t.Fatal(err)
	}
	write(t, filepath.Join(dir, "mmdvm.d"), "10-local.conf", "[General]\nTimeout=999\n[LocalExtras]\nFoo=bar")

	paths := Paths{
		MMDVM: filepath.Join(etc, "MMDVM-Host.ini"), DMRGateway: filepath.Join(etc, "DMRGateway.ini"),
		YSFGateway: filepath.Join(etc, "YSFGateway.ini"), P25Gateway: filepath.Join(etc, "P25Gateway.ini"),
		NXDNGateway: filepath.Join(etc, "NXDNGateway.ini"), DStarGateway: filepath.Join(etc, "dstargateway.cfg"),
		M17Gateway: filepath.Join(etc, "M17Gateway.ini"), DAPNETGateway: filepath.Join(etc, "DAPNETGateway.ini"), OverridesDir: dir,
	}

	warnings, err := m.WriteFiles(paths)
	if err != nil {
		t.Fatal(err)
	}
	if len(warnings) != 0 {
		t.Errorf("unexpected warnings: %v", warnings)
	}
	got, err := os.ReadFile(paths.MMDVM)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "Timeout=999") || !strings.Contains(string(got), "[LocalExtras]\nFoo=bar") {
		t.Errorf("override not merged into written file:\n%s", got)
	}

	// Overrides() must report the same edits without writing.
	applied, _, err := m.Overrides(paths)
	if err != nil {
		t.Fatal(err)
	}
	if len(applied) != 2 {
		t.Fatalf("Overrides() = %d records, want 2: %+v", len(applied), applied)
	}
	for _, a := range applied {
		if a.Daemon != "mmdvm" || a.Source != "10-local.conf" {
			t.Errorf("record has wrong provenance: %+v", a)
		}
	}

	// "Apply an update": re-render + re-merge over the same store and fragments ⇒
	// byte-identical file (the #2 acceptance).
	if _, err := m.WriteFiles(paths); err != nil {
		t.Fatal(err)
	}
	got2, _ := os.ReadFile(paths.MMDVM)
	if string(got) != string(got2) {
		t.Errorf("re-apply not byte-identical (update-survival):\n--- first ---\n%s\n--- second ---\n%s", got, got2)
	}
}

// With no OverridesDir the pipeline emits the pure render (inertness at the
// pipeline level, matching tests that pass Paths without an override root).
func TestWriteFiles_NoOverridesDir(t *testing.T) {
	m := fixture()
	etc := t.TempDir()
	paths := Paths{
		MMDVM: filepath.Join(etc, "MMDVM-Host.ini"), DMRGateway: filepath.Join(etc, "DMRGateway.ini"),
		YSFGateway: filepath.Join(etc, "YSFGateway.ini"), P25Gateway: filepath.Join(etc, "P25Gateway.ini"),
		NXDNGateway: filepath.Join(etc, "NXDNGateway.ini"), DStarGateway: filepath.Join(etc, "dstargateway.cfg"),
		M17Gateway: filepath.Join(etc, "M17Gateway.ini"), DAPNETGateway: filepath.Join(etc, "DAPNETGateway.ini"),
	}
	if _, err := m.WriteFiles(paths); err != nil {
		t.Fatal(err)
	}
	got, _ := os.ReadFile(paths.MMDVM)
	if string(got) != m.RenderMMDVM() {
		t.Errorf("no override dir should emit the pure render")
	}
	applied, _, err := m.Overrides(paths)
	if err != nil || len(applied) != 0 {
		t.Errorf("Overrides() with no dir = %v, %v; want empty", applied, err)
	}
}

// --- test helpers ---

func write(t *testing.T, dir, name, content string) {
	t.Helper()
	if err := os.WriteFile(filepath.Join(dir, name), []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
}
