package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// WriteFiles renders the model and writes both INI files atomically (write to a
// temp file in the same directory, then rename). A crash mid-apply therefore
// never leaves a daemon reading a half-written config.
func (m *Model) WriteFiles(mmdvmPath, dmrgatewayPath, ysfgatewayPath, p25gatewayPath, nxdngatewayPath string) error {
	if err := writeAtomic(mmdvmPath, m.RenderMMDVM()); err != nil {
		return err
	}
	if err := writeAtomic(dmrgatewayPath, m.RenderDMRGateway()); err != nil {
		return err
	}
	if err := writeAtomic(ysfgatewayPath, m.RenderYSFGateway()); err != nil {
		return err
	}
	if err := writeAtomic(p25gatewayPath, m.RenderP25Gateway()); err != nil {
		return err
	}
	return writeAtomic(nxdngatewayPath, m.RenderNXDNGateway())
}

func writeAtomic(path, content string) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".waypoint-*.tmp")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName) // no-op after a successful rename
	if _, err := tmp.WriteString(content); err != nil {
		tmp.Close()
		return err
	}
	// Leave the 0600 CreateTemp mode: the rendered DMRGateway.ini carries the
	// upstream network password, so the generated files stay root-only.
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}

// generatedHeader tops every rendered file: these are compiled outputs of the
// store, and hand edits are lost on the next apply (the override layer is the
// escape hatch — RFC-0001).
const generatedHeader = `; Generated by waypointd from the configuration store — do NOT edit.
; Edits are overwritten on the next Apply. Use the override layer instead.
`

// RenderMMDVM renders a complete MMDVM-Host.ini from the model. It is a pure
// function: the same model always yields byte-identical output. Managed keys
// come from the model; fixed operational keys come from constants here.
func (m *Model) RenderMMDVM() string {
	var b strings.Builder
	b.WriteString(generatedHeader)

	sect(&b, "General",
		kv("Callsign", m.General.Callsign),
		kv("Id", m.General.ID),
		kv("Timeout", def(m.General.Timeout, "240")),
		kb("Duplex", m.General.Duplex),
		kv("RFModeHang", def(m.General.RFModeHang, "300")),
		kv("NetModeHang", def(m.General.NetModeHang, "300")),
		kv("Display", "None"),
		kv("Daemon", "0"),
	)
	sect(&b, "Info",
		kv("RXFrequency", m.Modem.RXFreqHz),
		kv("TXFrequency", m.Modem.TXFreqHz),
		kv("Power", def(m.General.Power, "1")),
		kv("Location", m.General.Location),
		kv("URL", m.General.URL),
	)
	sect(&b, "Log",
		kv("MQTTLevel", "1"),
		kv("DisplayLevel", "0"),
	)
	sect(&b, "MQTT",
		kv("Host", "127.0.0.1"),
		kv("Port", "1883"),
		kv("Auth", "0"),
		kv("Name", "mmdvm"),
		kv("Keepalive", "60"),
	)
	sect(&b, "DMR Id Lookup",
		kv("File", "/usr/local/etc/DMRIds.dat"),
		kv("Time", "24"),
	)
	sect(&b, "Modem",
		kv("Protocol", "uart"),
		kv("UARTPort", def(m.Modem.Port, "/dev/ttyAMA0")),
		kv("UARTSpeed", def(m.Modem.UARTSpeed, "115200")),
		kb("TXInvert", m.Modem.TXInvert),
		kb("RXInvert", m.Modem.RXInvert),
		kb("PTTInvert", m.Modem.PTTInvert),
		kv("RXOffset", def(m.Modem.RXOffset, "0")),
		kv("TXOffset", def(m.Modem.TXOffset, "0")),
		kv("RXLevel", def(m.Modem.RXLevel, "50")),
		kv("TXLevel", def(m.Modem.TXLevel, "50")),
		kv("RSSIMappingFile", "/usr/local/etc/RSSI.dat"),
	)

	modeSect(&b, "D-Star", m.Modes.DStar)
	sect(&b, "DMR",
		kb("Enable", m.Modes.DMR),
		kv("ColorCode", def(m.DMR.ColorCode, "1")),
		kv("Id", firstNonEmpty(m.DMR.ID, m.General.ID)),
		kb("SelfOnly", m.DMR.SelfOnly),
		kb("EmbeddedLCOnly", m.DMR.EmbeddedLCOnly),
		kb("DumpTAData", m.DMR.DumpTAData),
	)
	sect(&b, "System Fusion",
		kb("Enable", m.Modes.YSF),
		kb("LowDeviation", m.YSF.LowDeviation),
		kb("SelfOnly", m.YSF.SelfOnly),
		kv("TXHang", def(m.YSF.TXHang, "4")),
		kb("RemoteGateway", m.YSF.RemoteGateway),
		kv("ModeHang", def(m.YSF.ModeHang, "20")),
	)
	sect(&b, "P25",
		kb("Enable", m.Modes.P25),
		kv("NAC", def(m.P25.NAC, "293")),
		kb("SelfOnly", m.P25.SelfOnly),
		kb("OverrideUIDCheck", m.P25.OverrideUIDCheck),
		kb("RemoteGateway", m.P25.RemoteGateway),
		kv("TXHang", def(m.P25.TXHang, "5")),
	)
	sect(&b, "NXDN",
		kb("Enable", m.Modes.NXDN),
		kv("RAN", def(m.NXDN.RAN, "1")),
		kb("SelfOnly", m.NXDN.SelfOnly),
		kb("RemoteGateway", m.NXDN.RemoteGateway),
		kv("TXHang", def(m.NXDN.TXHang, "5")),
	)
	modeSect(&b, "M17", m.Modes.M17)
	modeSect(&b, "POCSAG", m.Modes.POCSAG)
	modeSect(&b, "FM", m.Modes.FM)

	sect(&b, "DMR Network",
		kb("Enable", m.Modes.DMR),
		kv("LocalAddress", "127.0.0.1"),
		kv("LocalPort", def(m.DMRNet.LocalPort, "62032")),
		kv("GatewayAddress", def(m.DMRNet.GatewayAddress, "127.0.0.1")),
		kv("GatewayPort", def(m.DMRNet.GatewayPort, "62031")),
		kv("Jitter", def(m.DMRNet.Jitter, "360")),
		kb("Slot1", m.DMRNet.Slot1),
		kb("Slot2", m.DMRNet.Slot2),
	)
	// The System Fusion network talks to YSFGateway on the fixed 3200/4200 pair.
	sect(&b, "System Fusion Network",
		kb("Enable", m.Modes.YSF),
		kv("LocalAddress", "127.0.0.1"),
		kv("LocalPort", ysfMMDVMLocalPort),
		kv("GatewayAddress", "127.0.0.1"),
		kv("GatewayPort", ysfMMDVMGatewayPort),
		kv("ModeHang", def(m.YSF.ModeHang, "20")),
	)
	// The P25 network talks to P25Gateway on the fixed 32010/42020 pair.
	sect(&b, "P25 Network",
		kb("Enable", m.Modes.P25),
		kv("LocalAddress", "127.0.0.1"),
		kv("LocalPort", p25MMDVMLocalPort),
		kv("GatewayAddress", "127.0.0.1"),
		kv("GatewayPort", p25MMDVMGatewayPort),
		kv("Debug", "0"),
	)
	// The NXDN network talks to NXDNGateway on the fixed 14021/14020 pair.
	// Protocol=Icom is the MMDVM transport (NXDNGateway's RptProtocol matches).
	sect(&b, "NXDN Network",
		kb("Enable", m.Modes.NXDN),
		kv("Protocol", "Icom"),
		kv("LocalAddress", "127.0.0.1"),
		kv("LocalPort", nxdnMMDVMLocalPort),
		kv("GatewayAddress", "127.0.0.1"),
		kv("GatewayPort", nxdnMMDVMGatewayPort),
		kv("Debug", "0"),
	)
	return b.String()
}

// Fixed loopback ports between MMDVM-Host and its gateways (the g4klx convention).
const (
	ysfMMDVMLocalPort   = "3200" // MMDVM-Host listens here; YSFGateway RptPort
	ysfMMDVMGatewayPort = "4200" // YSFGateway listens here; MMDVM-Host sends here

	p25MMDVMLocalPort   = "32010" // MMDVM-Host listens here; P25Gateway RptPort
	p25MMDVMGatewayPort = "42020" // P25Gateway listens here; MMDVM-Host sends here

	nxdnMMDVMLocalPort   = "14021" // MMDVM-Host listens here; NXDNGateway RptPort
	nxdnMMDVMGatewayPort = "14020" // NXDNGateway listens here; MMDVM-Host sends here
)

// RenderYSFGateway renders a complete YSFGateway.ini from the model. Callsign,
// ID, and frequencies come from the shared station config; the rest from the
// YSFGateway section. Reflector/room hostlists are managed files on disk.
func (m *Model) RenderYSFGateway() string {
	var b strings.Builder
	b.WriteString(generatedHeader)

	sect(&b, "General",
		kv("Callsign", m.General.Callsign),
		kv("Suffix", def(m.YSFGW.Suffix, "RPT")),
		kv("Id", m.General.ID),
		kv("RptAddress", "127.0.0.1"),
		kv("RptPort", ysfMMDVMLocalPort),
		kv("LocalAddress", "127.0.0.1"),
		kv("LocalPort", ysfMMDVMGatewayPort),
		kb("WiresXCommandPassthrough", m.YSFGW.WiresXPassthrough),
		kb("WiresXMakeUpper", m.YSFGW.WiresXMakeUpper),
		kv("Daemon", "0"),
	)
	sect(&b, "Info",
		kv("RXFrequency", m.Modem.RXFreqHz),
		kv("TXFrequency", m.Modem.TXFreqHz),
		kv("Power", def(m.General.Power, "1")),
		kv("Name", def(m.General.Location, "Waypoint")),
	)
	sect(&b, "Log",
		kv("MQTTLevel", "1"),
		kv("DisplayLevel", "0"),
	)
	sect(&b, "MQTT",
		kv("Address", "127.0.0.1"),
		kv("Port", "1883"),
		kv("Keepalive", "60"),
		kv("Auth", "0"),
		kv("Name", "ysf-gateway"),
	)
	sect(&b, "Network",
		kv("Startup", m.YSFGW.Startup),
		kb("Reconnect", m.YSFGW.Reconnect),
		kb("Revert", m.YSFGW.Revert),
		kv("InactivityTimeout", def(m.YSFGW.InactivityTimeout, "30")),
		kv("Debug", "0"),
	)
	sect(&b, "YSF Network",
		kb("Enable", m.YSFGW.YSFNetwork),
		kv("Port", "42000"),
		kv("Hosts", ysfHostsPath),
		kv("ReloadTime", "60"),
		kv("ParrotAddress", "127.0.0.1"),
		kv("ParrotPort", "42012"),
	)
	sect(&b, "FCS Network",
		kb("Enable", m.YSFGW.FCSNetwork),
		kv("Port", "42001"),
		kv("Rooms", fcsRoomsPath),
	)
	sect(&b, "APRS",
		kb("Enable", m.YSFGW.APRS),
		kv("Suffix", "Y"),
	)
	return b.String()
}

// Managed reflector/room hostlists, fetched and cached by waypointd. The pinned
// YSFGateway parses YSFHosts as JSON (data["reflectors"]).
const (
	ysfHostsPath = "/home/pi-star/waypoint/etc/YSFHosts.json"
	fcsRoomsPath = "/home/pi-star/waypoint/etc/FCSRooms.txt"
)

// Managed paths for P25Gateway. The pinned P25Gateway parses P25Hosts as JSON
// (data["reflectors"], each with designator/port/ipv4). Audio holds the spoken
// announcement clips; a missing directory only disables voice, it is not fatal.
const (
	p25HostsPath = "/home/pi-star/waypoint/etc/P25Hosts.json"
	p25AudioDir  = "/home/pi-star/waypoint/etc/P25Audio"
)

// RenderP25Gateway renders a complete P25Gateway.ini from the model. Callsign
// and frequencies come from the shared station config; the rest from the P25
// mode/gateway sections. The reflector hostlist is a managed JSON file on disk.
func (m *Model) RenderP25Gateway() string {
	var b strings.Builder
	b.WriteString(generatedHeader)

	sect(&b, "General",
		kv("Callsign", m.General.Callsign),
		kv("RptAddress", "127.0.0.1"),
		kv("RptPort", p25MMDVMLocalPort),
		kv("LocalPort", p25MMDVMGatewayPort),
		kv("Debug", "0"),
		kv("Daemon", "0"),
	)
	sect(&b, "Id Lookup",
		kv("Name", "/usr/local/etc/DMRIds.dat"),
		kv("Time", "24"),
	)
	sect(&b, "Voice",
		kb("Enabled", m.P25GW.Voice),
		kv("Language", "en_GB"),
		kv("Directory", p25AudioDir),
	)
	sect(&b, "Log",
		kv("MQTTLevel", "1"),
		kv("DisplayLevel", "0"),
	)
	sect(&b, "MQTT",
		kv("Address", "127.0.0.1"),
		kv("Port", "1883"),
		kv("Keepalive", "60"),
		kv("Auth", "0"),
		kv("Name", "p25-gateway"),
	)
	// Parrot (local echo, TG9990-style) runs on 42011; P252DMR is omitted so no
	// dead cross-mode TG is advertised. Static holds any startup/auto-link TGs.
	sect(&b, "Network",
		kv("Port", "42010"),
		kv("HostsFile1", p25HostsPath),
		// HostsFile2 is the optional local/private TG list. We keep it as an empty
		// source (/dev/null) so P25Gateway's unconditional parseHosts() call opens
		// cleanly instead of logging "Unable to open the Hosts file".
		kv("HostsFile2", "/dev/null"),
		kv("ReloadTime", "60"),
		kv("ParrotAddress", "127.0.0.1"),
		kv("ParrotPort", "42011"),
		kv("Static", m.P25GW.Static),
		kv("RFHangTime", def(m.P25GW.RFHangTime, "120")),
		kv("NetHangTime", def(m.P25GW.NetHangTime, "60")),
		kv("Debug", "0"),
	)
	sect(&b, "Remote Commands",
		kv("Enable", "0"),
	)
	return b.String()
}

// Managed paths for NXDNGateway. Like P25Gateway, NXDNGateway parses NXDNHosts
// as JSON (Reflectors.cpp parseJSON reads data["reflectors"], each with a
// designator/port/ipv4). Audio holds the spoken announcement clips; a missing
// directory only disables voice (NXDNGateway nulls it and continues).
const (
	nxdnHostsPath = "/home/pi-star/waypoint/etc/NXDNHosts.json"
	nxdnAudioDir  = "/home/pi-star/waypoint/etc/NXDNAudio"
)

// RenderNXDNGateway renders a complete NXDNGateway.ini from the model. Callsign
// comes from the shared station config; the rest from the NXDN mode/gateway
// sections. The reflector hostlist is a managed JSON file on disk. RptProtocol
// is Icom, the MMDVM transport (mirrors MMDVM-Host's [NXDN Network] Protocol).
func (m *Model) RenderNXDNGateway() string {
	var b strings.Builder
	b.WriteString(generatedHeader)

	sect(&b, "General",
		kv("Callsign", m.General.Callsign),
		kv("Suffix", "NXDN"),
		kv("RptProtocol", "Icom"),
		kv("RptAddress", "127.0.0.1"),
		kv("RptPort", nxdnMMDVMLocalPort),
		kv("LocalPort", nxdnMMDVMGatewayPort),
		kv("Debug", "0"),
		kv("Daemon", "0"),
	)
	// NXDN callsign lookup shares the RadioID DMR ID space; NXDNLookup's parser
	// splits on comma/tab, so it reads the tab-separated DMRIds.dat directly.
	sect(&b, "Id Lookup",
		kv("Name", "/usr/local/etc/DMRIds.dat"),
		kv("Time", "24"),
	)
	sect(&b, "Voice",
		kb("Enabled", m.NXDNGW.Voice),
		kv("Language", "en_GB"),
		kv("Directory", nxdnAudioDir),
	)
	sect(&b, "Log",
		kv("MQTTLevel", "1"),
		kv("DisplayLevel", "0"),
	)
	sect(&b, "MQTT",
		kv("Address", "127.0.0.1"),
		kv("Port", "1883"),
		kv("Keepalive", "60"),
		kv("Auth", "0"),
		kv("Name", "nxdn-gateway"),
	)
	// Parrot (local echo, TG10) runs on 42021; NXDN2DMR is omitted so no dead
	// cross-mode TG is advertised (Reflectors.cpp only adds TG20 when its port
	// is set). Static holds any startup/auto-link TGs (empty by default).
	sect(&b, "Network",
		kv("Port", "14050"),
		kv("HostsFile1", nxdnHostsPath),
		// HostsFile2 is the optional local/private TG list. We keep it as an empty
		// source (/dev/null) so NXDNGateway's unconditional parseHosts() opens
		// cleanly instead of logging "Unable to open the Hosts file".
		kv("HostsFile2", "/dev/null"),
		kv("ReloadTime", "60"),
		kv("ParrotAddress", "127.0.0.1"),
		kv("ParrotPort", "42021"),
		kv("Static", m.NXDNGW.Static),
		kv("RFHangTime", def(m.NXDNGW.RFHangTime, "120")),
		kv("NetHangTime", def(m.NXDNGW.NetHangTime, "60")),
		kv("Debug", "0"),
	)
	sect(&b, "GPSD",
		kv("Enable", "0"),
	)
	sect(&b, "Remote Commands",
		kv("Enable", "0"),
	)
	return b.String()
}

// RenderDMRGateway renders a complete DMRGateway.ini from the model.
func (m *Model) RenderDMRGateway() string {
	var b strings.Builder
	b.WriteString(generatedHeader)

	sect(&b, "General",
		kv("RptAddress", "127.0.0.1"),
		kv("RptPort", def(m.DMRNet.LocalPort, "62032")),
		kv("LocalAddress", "127.0.0.1"),
		kv("LocalPort", def(m.DMRNet.GatewayPort, "62031")),
		kv("Timeout", "10"),
		kv("Daemon", "0"),
	)
	sect(&b, "Log",
		kv("MQTTLevel", "1"),
		kv("DisplayLevel", "0"),
	)
	sect(&b, "MQTT",
		kv("Address", "127.0.0.1"),
		kv("Port", "1883"),
		kv("Keepalive", "60"),
		kv("Auth", "0"),
		kv("Name", "dmr-gateway"),
	)

	for i, n := range m.Networks {
		lines := []string{
			kv("Name", n.Name),
			kv("Address", n.Address),
			kv("Port", def(n.Port, "62031")),
			kv("Password", n.Password),
			kv("Id", m.DMR.ID),
			kb("Enabled", n.Enabled),
			kb("Debug", false),
		}
		lines = append(lines, n.Rewrites...) // rewrites preserved verbatim, sorted at import
		sect(&b, fmt.Sprintf("DMR Network %d", i+1), lines...)
	}
	return b.String()
}

// --- rendering helpers (deterministic) -----------------------------------

func sect(b *strings.Builder, name string, lines ...string) {
	b.WriteString("\n[")
	b.WriteString(name)
	b.WriteString("]\n")
	for _, l := range lines {
		b.WriteString(l)
		b.WriteByte('\n')
	}
}

func modeSect(b *strings.Builder, name string, on bool) {
	sect(b, name, kb("Enable", on))
}

func kv(k, v string) string { return k + "=" + v }

func kb(k string, on bool) string {
	if on {
		return k + "=1"
	}
	return k + "=0"
}

func def(v, d string) string {
	if strings.TrimSpace(v) == "" {
		return d
	}
	return v
}
