package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// WriteFiles renders the model and writes both INI files atomically (write to a
// temp file in the same directory, then rename). A crash mid-apply therefore
// never leaves a daemon reading a half-written config.
func (m *Model) WriteFiles(mmdvmPath, dmrgatewayPath string) error {
	if err := writeAtomic(mmdvmPath, m.RenderMMDVM()); err != nil {
		return err
	}
	return writeAtomic(dmrgatewayPath, m.RenderDMRGateway())
}

func writeAtomic(path, content string) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".waypoint-*.tmp")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName) // no-op after a successful rename
	if _, err := tmp.WriteString(content); err != nil {
		tmp.Close()
		return err
	}
	// Leave the 0600 CreateTemp mode: the rendered DMRGateway.ini carries the
	// upstream network password, so the generated files stay root-only.
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}

// generatedHeader tops every rendered file: these are compiled outputs of the
// store, and hand edits are lost on the next apply (the override layer is the
// escape hatch — RFC-0001).
const generatedHeader = `; Generated by waypointd from the configuration store — do NOT edit.
; Edits are overwritten on the next Apply. Use the override layer instead.
`

// RenderMMDVM renders a complete MMDVM-Host.ini from the model. It is a pure
// function: the same model always yields byte-identical output. Managed keys
// come from the model; fixed operational keys come from constants here.
func (m *Model) RenderMMDVM() string {
	var b strings.Builder
	b.WriteString(generatedHeader)

	sect(&b, "General",
		kv("Callsign", m.General.Callsign),
		kv("Id", m.General.ID),
		kv("Timeout", def(m.General.Timeout, "240")),
		kb("Duplex", m.General.Duplex),
		kv("RFModeHang", def(m.General.RFModeHang, "300")),
		kv("NetModeHang", def(m.General.NetModeHang, "300")),
		kv("Display", "None"),
		kv("Daemon", "0"),
	)
	sect(&b, "Info",
		kv("RXFrequency", m.Modem.RXFreqHz),
		kv("TXFrequency", m.Modem.TXFreqHz),
		kv("Power", def(m.General.Power, "1")),
		kv("Location", m.General.Location),
		kv("URL", m.General.URL),
	)
	sect(&b, "Log",
		kv("MQTTLevel", "1"),
		kv("DisplayLevel", "0"),
	)
	sect(&b, "MQTT",
		kv("Host", "127.0.0.1"),
		kv("Port", "1883"),
		kv("Auth", "0"),
		kv("Name", "mmdvm"),
		kv("Keepalive", "60"),
	)
	sect(&b, "DMR Id Lookup",
		kv("File", "/usr/local/etc/DMRIds.dat"),
		kv("Time", "24"),
	)
	sect(&b, "Modem",
		kv("Protocol", "uart"),
		kv("UARTPort", def(m.Modem.Port, "/dev/ttyAMA0")),
		kv("UARTSpeed", def(m.Modem.UARTSpeed, "115200")),
		kb("TXInvert", m.Modem.TXInvert),
		kb("RXInvert", m.Modem.RXInvert),
		kb("PTTInvert", m.Modem.PTTInvert),
		kv("RXOffset", def(m.Modem.RXOffset, "0")),
		kv("TXOffset", def(m.Modem.TXOffset, "0")),
		kv("RXLevel", def(m.Modem.RXLevel, "50")),
		kv("TXLevel", def(m.Modem.TXLevel, "50")),
		kv("RSSIMappingFile", "/usr/local/etc/RSSI.dat"),
	)

	modeSect(&b, "D-Star", m.Modes.DStar)
	sect(&b, "DMR",
		kb("Enable", m.Modes.DMR),
		kv("ColorCode", def(m.DMR.ColorCode, "1")),
		kv("Id", firstNonEmpty(m.DMR.ID, m.General.ID)),
		kb("SelfOnly", m.DMR.SelfOnly),
		kb("EmbeddedLCOnly", m.DMR.EmbeddedLCOnly),
		kb("DumpTAData", m.DMR.DumpTAData),
	)
	modeSect(&b, "System Fusion", m.Modes.YSF)
	modeSect(&b, "P25", m.Modes.P25)
	modeSect(&b, "NXDN", m.Modes.NXDN)
	modeSect(&b, "M17", m.Modes.M17)
	modeSect(&b, "POCSAG", m.Modes.POCSAG)
	modeSect(&b, "FM", m.Modes.FM)

	sect(&b, "DMR Network",
		kb("Enable", m.Modes.DMR),
		kv("LocalAddress", "127.0.0.1"),
		kv("LocalPort", def(m.DMRNet.LocalPort, "62032")),
		kv("GatewayAddress", def(m.DMRNet.GatewayAddress, "127.0.0.1")),
		kv("GatewayPort", def(m.DMRNet.GatewayPort, "62031")),
		kv("Jitter", def(m.DMRNet.Jitter, "360")),
		kb("Slot1", m.DMRNet.Slot1),
		kb("Slot2", m.DMRNet.Slot2),
	)
	return b.String()
}

// RenderDMRGateway renders a complete DMRGateway.ini from the model.
func (m *Model) RenderDMRGateway() string {
	var b strings.Builder
	b.WriteString(generatedHeader)

	sect(&b, "General",
		kv("RptAddress", "127.0.0.1"),
		kv("RptPort", def(m.DMRNet.LocalPort, "62032")),
		kv("LocalAddress", "127.0.0.1"),
		kv("LocalPort", def(m.DMRNet.GatewayPort, "62031")),
		kv("Timeout", "10"),
		kv("Daemon", "0"),
	)
	sect(&b, "Log",
		kv("MQTTLevel", "1"),
		kv("DisplayLevel", "0"),
	)
	sect(&b, "MQTT",
		kv("Address", "127.0.0.1"),
		kv("Port", "1883"),
		kv("Keepalive", "60"),
		kv("Auth", "0"),
		kv("Name", "dmr-gateway"),
	)

	for i, n := range m.Networks {
		lines := []string{
			kv("Name", n.Name),
			kv("Address", n.Address),
			kv("Port", def(n.Port, "62031")),
			kv("Password", n.Password),
			kv("Id", m.DMR.ID),
			kb("Enabled", n.Enabled),
			kb("Debug", false),
		}
		lines = append(lines, n.Rewrites...) // rewrites preserved verbatim, sorted at import
		sect(&b, fmt.Sprintf("DMR Network %d", i+1), lines...)
	}
	return b.String()
}

// --- rendering helpers (deterministic) -----------------------------------

func sect(b *strings.Builder, name string, lines ...string) {
	b.WriteString("\n[")
	b.WriteString(name)
	b.WriteString("]\n")
	for _, l := range lines {
		b.WriteString(l)
		b.WriteByte('\n')
	}
}

func modeSect(b *strings.Builder, name string, on bool) {
	sect(b, name, kb("Enable", on))
}

func kv(k, v string) string { return k + "=" + v }

func kb(k string, on bool) string {
	if on {
		return k + "=1"
	}
	return k + "=0"
}

func def(v, d string) string {
	if strings.TrimSpace(v) == "" {
		return d
	}
	return v
}
