package netconfig

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRenderTimesyncd(t *testing.T) {
	out := RenderTimesyncd(NTP{Enabled: true, Servers: []string{"time.cloudflare.com", "pool.ntp.org"}})
	for _, want := range []string{"# Generated by waypointd", "[Time]\n", "NTP=time.cloudflare.com pool.ntp.org\n"} {
		if !strings.Contains(out, want) {
			t.Errorf("timesyncd render missing %q\n%s", want, out)
		}
	}
	// No servers → header + section, no NTP= line (vendor defaults stay in effect).
	if strings.Contains(RenderTimesyncd(NTP{Enabled: true}), "NTP=") {
		t.Error("no-servers render should not emit an NTP= line")
	}
	// Blank server entries are dropped.
	out = RenderTimesyncd(NTP{Servers: []string{"", "  ", "a.ntp"}})
	if !strings.Contains(out, "NTP=a.ntp\n") {
		t.Errorf("blank servers not filtered: %q", out)
	}
}

// recordRunner records commands and answers "current value" queries so idempotency
// can be asserted (a matching current value should issue no set command).
type recordRunner struct {
	calls    []string
	curHost  string
	curTZ    string
	curNTP   string // ignored
	restarts int
}

func (r *recordRunner) run(name string, args ...string) (string, error) {
	joined := name + " " + strings.Join(args, " ")
	r.calls = append(r.calls, joined)
	switch {
	case name == "hostnamectl" && len(args) == 1 && args[0] == "--static":
		return r.curHost, nil
	case strings.Contains(joined, "timedatectl show -p Timezone"):
		return r.curTZ, nil
	case strings.Contains(joined, "systemctl restart systemd-timesyncd"):
		r.restarts++
	}
	return "", nil
}

func (r *recordRunner) issued(substr string) bool {
	for _, c := range r.calls {
		if strings.Contains(c, substr) {
			return true
		}
	}
	return false
}

// Hostname apply is idempotent: same value → no set-hostname.
func TestApplyHostnameIdempotent(t *testing.T) {
	r := &recordRunner{curHost: "wpsd"}
	changed, err := ApplyHostname(r.run, "wpsd")
	if err != nil || changed {
		t.Fatalf("same hostname should be a no-op: changed=%v err=%v", changed, err)
	}
	if r.issued("set-hostname") {
		t.Error("set-hostname must not be issued when the value is unchanged")
	}
	// A different value sets it.
	r = &recordRunner{curHost: "wpsd"}
	changed, err = ApplyHostname(r.run, "newname")
	if err != nil || !changed {
		t.Fatalf("changed hostname should apply: changed=%v err=%v", changed, err)
	}
	if !r.issued("set-hostname newname") {
		t.Errorf("set-hostname not issued: %v", r.calls)
	}
	// Blank is left alone.
	r = &recordRunner{curHost: "wpsd"}
	if changed, _ := ApplyHostname(r.run, "  "); changed || r.issued("set-hostname") {
		t.Error("blank hostname should be left untouched")
	}
}

// Timezone apply is idempotent: same value → no set-timezone.
func TestApplyTimezoneIdempotent(t *testing.T) {
	r := &recordRunner{curTZ: "America/New_York"}
	if changed, _ := ApplyTimezone(r.run, "America/New_York"); changed || r.issued("set-timezone") {
		t.Error("same timezone should be a no-op")
	}
	r = &recordRunner{curTZ: "America/New_York"}
	if changed, _ := ApplyTimezone(r.run, "Europe/London"); !changed || !r.issued("set-timezone Europe/London") {
		t.Errorf("changed timezone should apply: %v", r.calls)
	}
}

// ApplyNTP writes the drop-in, sets the enable state, and only restarts when the
// file changed; a second identical apply is a no-op (no restart).
func TestApplyNTPChangeGatedRestart(t *testing.T) {
	dir := t.TempDir()
	conf := filepath.Join(dir, "waypoint.conf")
	r := &recordRunner{}
	changed, err := ApplyNTP(r.run, conf, NTP{Enabled: true, Servers: []string{"a.ntp"}})
	if err != nil || !changed {
		t.Fatalf("first apply should change: changed=%v err=%v", changed, err)
	}
	if r.restarts != 1 {
		t.Errorf("first apply should restart timesyncd once, got %d", r.restarts)
	}
	if !r.issued("timedatectl set-ntp true") {
		t.Errorf("set-ntp true not issued: %v", r.calls)
	}
	if b, _ := os.ReadFile(conf); !strings.Contains(string(b), "NTP=a.ntp") {
		t.Errorf("conf not written: %q", b)
	}
	// Second identical apply: no file change ⇒ no restart.
	r2 := &recordRunner{}
	changed, _ = ApplyNTP(r2.run, conf, NTP{Enabled: true, Servers: []string{"a.ntp"}})
	if changed || r2.restarts != 0 {
		t.Errorf("identical NTP apply should be a no-op: changed=%v restarts=%d", changed, r2.restarts)
	}
}

// ApplyHost is a no-op (no set commands) when everything already matches.
func TestApplyHostAllIdempotent(t *testing.T) {
	dir := t.TempDir()
	conf := filepath.Join(dir, "waypoint.conf")
	ntp := NTP{Enabled: true, Servers: []string{"a.ntp"}}
	// Prime the conf file so NTP is already in effect.
	if _, err := writeAtomicIfChanged(conf, RenderTimesyncd(ntp), 0o644); err != nil {
		t.Fatal(err)
	}
	r := &recordRunner{curHost: "wpsd", curTZ: "UTC"}
	changed, err := ApplyHost(r.run, conf, Host{Hostname: "wpsd", Timezone: "UTC"}, ntp)
	if err != nil {
		t.Fatal(err)
	}
	if changed {
		t.Error("everything already applied → ApplyHost should report no change")
	}
	if r.issued("set-hostname") || r.issued("set-timezone") || r.restarts != 0 {
		t.Errorf("no set/restart commands expected on a fully-idempotent apply: %v", r.calls)
	}
}
