package netconfig

import (
	"os"
	"path/filepath"
	"strings"
)

// This file is the host domain's DIRECT apply path — the third apply mechanism in
// Waypoint, alongside the radio family's "render INI + restart unit" and the
// network family's "render keyfile + confirm-or-revert". Hostname, timezone, and
// NTP cannot strand the node, so they apply immediately with no guard. They are
// deliberately tiny and IDEMPOTENT: applying the value already in effect issues no
// command, so a repeated apply is a genuine no-op.

// timesyncdHeader tops the generated timesyncd drop-in (a compiled output like the
// keyfiles). The file is world-readable (0644) — no secret — unlike the keyfiles.
const timesyncdHeader = `# Generated by waypointd from the configuration store — do NOT edit.
# Edits are overwritten on the next Apply.
`

// RenderTimesyncd compiles the NTP config into a systemd-timesyncd drop-in body
// (a [Time] section with an NTP= line). It is pure: same NTP ⇒ identical output.
// With no servers the drop-in carries just the header + section, leaving
// timesyncd's vendor/fallback servers in effect.
func RenderTimesyncd(n NTP) string {
	var b strings.Builder
	b.WriteString(timesyncdHeader)
	b.WriteString("[Time]\n")
	if servers := nonBlank(n.Servers); len(servers) > 0 {
		b.WriteString("NTP=")
		b.WriteString(strings.Join(servers, " "))
		b.WriteByte('\n')
	}
	return b.String()
}

// ApplyNTP writes the timesyncd drop-in, sets the client enable state, and — only
// when the drop-in actually changed — restarts systemd-timesyncd so new servers
// take effect. set-ntp is idempotent in systemd; the change-gated restart keeps a
// no-op apply from bouncing the clock sync.
func ApplyNTP(run Runner, confPath string, n NTP) (changed bool, err error) {
	if err := os.MkdirAll(filepath.Dir(confPath), 0o755); err != nil {
		return false, err
	}
	changed, err = writeAtomicIfChanged(confPath, RenderTimesyncd(n), 0o644)
	if err != nil {
		return false, err
	}
	if _, err := run("timedatectl", "set-ntp", boolWord(n.Enabled)); err != nil {
		return changed, err
	}
	if changed {
		if _, err := run("systemctl", "restart", "systemd-timesyncd"); err != nil {
			return changed, err
		}
	}
	return changed, nil
}

// ApplyHostname sets the static hostname via hostnamectl, but only if it differs
// from the current one (idempotent). A blank hostname means "leave it".
func ApplyHostname(run Runner, hostname string) (changed bool, err error) {
	hostname = strings.TrimSpace(hostname)
	if hostname == "" {
		return false, nil
	}
	cur, _ := run("hostnamectl", "--static")
	if strings.TrimSpace(cur) == hostname {
		return false, nil
	}
	if _, err := run("hostnamectl", "set-hostname", hostname); err != nil {
		return false, err
	}
	return true, nil
}

// ApplyTimezone sets the timezone via timedatectl, only if it differs from the
// current one (idempotent). A blank timezone means "leave it". An invalid zone is
// rejected by timedatectl itself (surfaced as the error).
func ApplyTimezone(run Runner, tz string) (changed bool, err error) {
	tz = strings.TrimSpace(tz)
	if tz == "" {
		return false, nil
	}
	cur, _ := run("timedatectl", "show", "-p", "Timezone", "--value")
	if strings.TrimSpace(cur) == tz {
		return false, nil
	}
	if _, err := run("timedatectl", "set-timezone", tz); err != nil {
		return false, err
	}
	return true, nil
}

// ApplyHost runs the whole direct-apply set (hostname, timezone, NTP) in order and
// reports whether anything actually changed. Each step is idempotent, so calling
// this with the already-applied values is a no-op that issues no set commands.
func ApplyHost(run Runner, timesyncdConf string, h Host, n NTP) (changed bool, err error) {
	hc, err := ApplyHostname(run, h.Hostname)
	if err != nil {
		return false, err
	}
	tc, err := ApplyTimezone(run, h.Timezone)
	if err != nil {
		return false, err
	}
	nc, err := ApplyNTP(run, timesyncdConf, n)
	if err != nil {
		return false, err
	}
	return hc || tc || nc, nil
}

// ListTimezones returns the tz-database zones (timedatectl list-timezones, which
// reads /usr/share/zoneinfo) for the searchable timezone picker.
func ListTimezones(run Runner) ([]string, error) {
	out, err := run("timedatectl", "list-timezones")
	if err != nil {
		return nil, err
	}
	return splitLines(out), nil
}

// boolWord renders systemd's on/off word for set-ntp.
func boolWord(v bool) string {
	if v {
		return "true"
	}
	return "false"
}

// nonBlank drops empty/whitespace entries from a string slice (NTP servers).
func nonBlank(in []string) []string {
	var out []string
	for _, s := range in {
		if strings.TrimSpace(s) != "" {
			out = append(out, strings.TrimSpace(s))
		}
	}
	return out
}
