package netconfig

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// sampleModel is a populated model whose fields are all non-default, so a
// round-trip cannot be masked by a rendered default filling an empty field.
func sampleModel() Model {
	return Model{
		Host: Host{Hostname: "waypoint-node", Timezone: "America/New_York"},
		NTP:  NTP{Enabled: true, Servers: []string{"time.cloudflare.com", "pool.ntp.org"}},
		Connections: []Connection{
			{
				Name:        "lan",
				Type:        TypeEthernet,
				Interface:   "eth0",
				Autoconnect: true,
				IPv4: IPv4{
					Method: "manual", Address: "192.168.1.50", Prefix: "24",
					Gateway: "192.168.1.1", DNS: []string{"1.1.1.1", "8.8.8.8"},
				},
			},
			{
				Name:        "wifi-home",
				Type:        TypeWiFi,
				Autoconnect: true,
				IPv4:        IPv4{Method: "auto", DNS: []string{"9.9.9.9"}},
				WiFi:        WiFi{SSID: "MyNetwork", PSK: "s3cr3tpass"},
			},
		},
	}
}

// Rendering is a pure function: the same model yields byte-identical output.
func TestRenderDeterministic(t *testing.T) {
	m := sampleModel()
	a := m.RenderTargets("/etc/NetworkManager/system-connections")
	b := m.RenderTargets("/etc/NetworkManager/system-connections")
	if !reflect.DeepEqual(a, b) {
		t.Fatal("render is not deterministic")
	}
}

// The per-profile UUID is derived from the name, so it is stable across renders
// (no random uuid that would break "unchanged store ⇒ no diff").
func TestUUIDDeterministic(t *testing.T) {
	if connUUID("lan") != connUUID("lan") {
		t.Fatal("connUUID must be deterministic for a name")
	}
	if connUUID("lan") == connUUID("wifi-home") {
		t.Fatal("distinct names must get distinct UUIDs")
	}
	u := connUUID("lan")
	if len(u) != 36 || u[14] != '5' { // RFC-4122 v5 marker in the version nibble
		t.Fatalf("connUUID %q is not a v5 UUID", u)
	}
}

// Every managed key round-trips: render → parse → reconstruct == original.
func TestKeyfileRoundTrip(t *testing.T) {
	m := sampleModel()
	for _, c := range m.Connections {
		got := parseKeyfile(c.render()).toConnection()
		if !reflect.DeepEqual(got, c) {
			t.Fatalf("connection %q did not round-trip:\n want %+v\n  got %+v", c.Name, c, got)
		}
	}
}

// The rendered keyfile carries the generated header and NM's required fixed keys.
func TestRenderShape(t *testing.T) {
	out := sampleModel().Connections[0].render()
	for _, want := range []string{
		"# Generated by waypointd",
		"[connection]\n",
		"id=waypoint-lan\n",
		"type=ethernet\n",
		"interface-name=eth0\n",
		"[ipv4]\n",
		"method=manual\n",
		"address1=192.168.1.50/24,192.168.1.1\n",
		"dns=1.1.1.1;8.8.8.8;\n",
		"[ipv6]\n",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("rendered keyfile missing %q\n---\n%s", want, out)
		}
	}
}

// A Wi-Fi profile renders the security group only when a PSK is set.
func TestRenderWiFiSecurity(t *testing.T) {
	c := sampleModel().Connections[1]
	out := c.render()
	for _, want := range []string{"[wifi]\n", "ssid=MyNetwork\n", "[wifi-security]\n", "key-mgmt=wpa-psk\n", "psk=s3cr3tpass\n"} {
		if !strings.Contains(out, want) {
			t.Errorf("wifi keyfile missing %q\n---\n%s", want, out)
		}
	}
	c.WiFi.PSK = ""
	if strings.Contains(c.render(), "[wifi-security]") {
		t.Error("no [wifi-security] group should render for an open/unset PSK")
	}
}

// Sync writes managed keyfiles at 0600 and prunes only waypoint-* profiles it no
// longer owns, never touching a hand-made profile.
func TestSyncWritesAndPrunesOnlyManaged(t *testing.T) {
	dir := t.TempDir()
	// A hand-made profile Waypoint must never touch.
	foreign := filepath.Join(dir, "my-home-wifi.nmconnection")
	if err := os.WriteFile(foreign, []byte("[connection]\nid=my-home-wifi\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	// A stale managed profile from a previous apply, no longer in the model.
	stale := filepath.Join(dir, FileName("old"))
	if err := os.WriteFile(stale, []byte("# Generated by waypointd\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	m := sampleModel()
	changed, err := m.Sync(dir)
	if err != nil {
		t.Fatalf("Sync: %v", err)
	}
	if !changed {
		t.Fatal("Sync should report a change on first write")
	}

	// Managed profiles written, at 0600.
	for _, c := range m.Connections {
		fi, err := os.Stat(filepath.Join(dir, FileName(c.Name)))
		if err != nil {
			t.Fatalf("managed profile %q not written: %v", c.Name, err)
		}
		if fi.Mode().Perm() != 0o600 {
			t.Errorf("profile %q mode = %v, want 0600", c.Name, fi.Mode().Perm())
		}
	}
	// Stale managed profile pruned; foreign profile untouched.
	if _, err := os.Stat(stale); !os.IsNotExist(err) {
		t.Error("stale waypoint-* profile should have been pruned")
	}
	if _, err := os.Stat(foreign); err != nil {
		t.Error("foreign profile must never be removed")
	}

	// A second Sync of the same model is a no-op (purity ⇒ no diff).
	changed, err = m.Sync(dir)
	if err != nil {
		t.Fatalf("second Sync: %v", err)
	}
	if changed {
		t.Error("re-Sync of an unchanged model should report no change")
	}
}

// Validate rejects the models the renderer cannot compile.
func TestValidate(t *testing.T) {
	cases := []struct {
		name string
		m    Model
		ok   bool
	}{
		{"good", sampleModel(), true},
		{"blank name", Model{Connections: []Connection{{Type: TypeEthernet}}}, false},
		{"dup name", Model{Connections: []Connection{{Name: "x", Type: TypeEthernet}, {Name: "x", Type: TypeWiFi}}}, false},
		{"bad type", Model{Connections: []Connection{{Name: "x", Type: "bridge"}}}, false},
		{"manual no addr", Model{Connections: []Connection{{Name: "x", Type: TypeEthernet, IPv4: IPv4{Method: "manual"}}}}, false},
	}
	for _, tc := range cases {
		err := tc.m.Validate()
		if tc.ok && err != nil {
			t.Errorf("%s: unexpected error %v", tc.name, err)
		}
		if !tc.ok && err == nil {
			t.Errorf("%s: expected a validation error", tc.name)
		}
	}
}
