package netconfig

import (
	"crypto/sha1"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// profilePrefix stamps every Waypoint-managed NetworkManager profile: the file
// is <prefix><name>.nmconnection and the [connection] id is <prefix><name>. It is
// the marker that lets netconfig own only what it created (managedName).
const profilePrefix = "waypoint-"

// keyfileExt is NetworkManager's keyfile extension. system-connections files must
// end in .nmconnection (or NM ignores them) and be 0600 root (or NM refuses to
// load a profile that carries a secret).
const keyfileExt = ".nmconnection"

// generatedHeader tops every rendered keyfile — the netconfig analogue of
// internal/config.generatedHeader, using keyfile-format ('#') comments. It marks
// the file as a compiled output and states the ownership rule inline so a human
// reading /etc/NetworkManager/system-connections knows which profiles are
// Waypoint's and which are hand-made.
const generatedHeader = `# Generated by waypointd from the configuration store — do NOT edit.
# Edits are overwritten on the next Apply. Waypoint manages only waypoint-* profiles.
`

// waypointNS is the fixed namespace for deriving deterministic per-profile UUIDs
// (RFC-4122 v5, SHA-1). A profile's UUID is a pure function of its name, so the
// same store renders byte-identical keyfiles — no random uuid would break the
// "unchanged store ⇒ no diff" property.
var waypointNS = [16]byte{0x77, 0x61, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x2d, 0x6e, 0x65, 0x74, 0x63, 0x66, 0x67, 0x00}

// connUUID derives a deterministic RFC-4122 v5 UUID from a profile name. NM
// requires [connection] uuid; deriving it keeps render pure.
func connUUID(name string) string {
	h := sha1.Sum(append(waypointNS[:], []byte(name)...))
	var b [16]byte
	copy(b[:], h[:16])
	b[6] = (b[6] & 0x0f) | 0x50 // version 5
	b[8] = (b[8] & 0x3f) | 0x80 // RFC-4122 variant
	return fmt.Sprintf("%x-%x-%x-%x-%x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16])
}

// FileName is the keyfile basename for a connection: waypoint-<name>.nmconnection.
func FileName(name string) string { return profilePrefix + name + keyfileExt }

// ProfileID is the [connection] id / nmcli name for a connection: waypoint-<name>.
// The apply path activates a change by bringing this id up on its device.
func ProfileID(name string) string { return profilePrefix + name }

// profileID is the internal alias used by the renderer.
func profileID(name string) string { return ProfileID(name) }

// ProfileIDs returns the NM connection ids for every managed connection, in model
// order — the set the apply path brings up so a saved change reaches the live
// device (not just the keyfile on disk).
func (m Model) ProfileIDs() []string {
	ids := make([]string, 0, len(m.Connections))
	for _, c := range m.Connections {
		ids = append(ids, ProfileID(c.Name))
	}
	return ids
}

// RenderConnection compiles one Connection into a NetworkManager keyfile. It is a
// pure function: the same Connection always yields byte-identical output (map
// iteration is never used; every list renders in a fixed order). Managed keys come
// from the model; NM's required-but-fixed keys are constants here.
func (c Connection) render() string {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("\n[connection]\n")
	writeKV(&b, "id", profileID(c.Name))
	writeKV(&b, "uuid", connUUID(c.Name))
	writeKV(&b, "type", string(c.Type))
	if c.Interface != "" {
		writeKV(&b, "interface-name", c.Interface)
	}
	writeKV(&b, "autoconnect", boolKey(c.Autoconnect))
	if p := strings.TrimSpace(c.Priority); p != "" && p != "0" {
		writeKV(&b, "autoconnect-priority", p)
	}

	if c.Type == TypeWiFi {
		b.WriteString("\n[wifi]\n")
		writeKV(&b, "mode", "infrastructure")
		writeKV(&b, "ssid", c.WiFi.SSID)
		if c.WiFi.Hidden {
			writeKV(&b, "hidden", "true")
		}
		if c.WiFi.PSK != "" {
			b.WriteString("\n[wifi-security]\n")
			writeKV(&b, "key-mgmt", "wpa-psk")
			writeKV(&b, "psk", c.WiFi.PSK)
		}
	}

	b.WriteString("\n[ipv4]\n")
	c.IPv4.render(&b)

	// IPv6 is left at NM's auto default for the foundation — a single fixed group
	// so the profile is complete and NM does not surface an "ipv6 disabled" quirk.
	b.WriteString("\n[ipv6]\n")
	writeKV(&b, "method", "auto")
	return b.String()
}

// render writes the [ipv4] body. method drives which keys appear: manual needs
// address1 (address/prefix,gateway); auto is DHCP. DNS renders for either method,
// with ignore-auto-dns on auto so operator-set servers are not merged with the
// DHCP-provided ones.
func (ip IPv4) render(b *strings.Builder) {
	method := ip.Method
	if method == "" {
		method = "auto"
	}
	writeKV(b, "method", method)
	if method == "manual" {
		prefix := ip.Prefix
		if prefix == "" {
			prefix = "24"
		}
		addr := ip.Address + "/" + prefix
		if ip.Gateway != "" {
			addr += "," + ip.Gateway
		}
		writeKV(b, "address1", addr)
	}
	if len(ip.DNS) > 0 {
		writeKV(b, "dns", strings.Join(ip.DNS, ";")+";")
		// With DHCP, operator DNS is an OVERRIDE: ignore-auto-dns drops the
		// DHCP-provided servers so only these are used (the prompt's "DNS override
		// also allowed with DHCP"). With a static address the servers stand alone.
		if method == "auto" {
			writeKV(b, "ignore-auto-dns", "true")
		}
	}
	if len(ip.SearchDomains) > 0 {
		writeKV(b, "dns-search", strings.Join(ip.SearchDomains, ";")+";")
	}
}

// writeKV writes one "key=value" line. NM keyfiles do not quote values and treat
// the first '=' as the separator, so no escaping is required for the fields
// Waypoint renders (ids, addresses, SSIDs, PSKs).
func writeKV(b *strings.Builder, k, v string) {
	b.WriteString(k)
	b.WriteByte('=')
	b.WriteString(v)
	b.WriteByte('\n')
}

// boolKey renders NM's keyfile boolean ("true"/"false").
func boolKey(v bool) string {
	if v {
		return "true"
	}
	return "false"
}

// Target is one rendered keyfile: its absolute path and content. Sync writes the
// set; the confirm-or-revert engine snapshots and restores it.
type Target struct {
	Path    string
	Content string
}

// RenderTargets returns one Target per managed connection, in model order, under
// dir. Every path is waypoint-*.nmconnection — the ownership marker — so a caller
// can trust that writing or removing these files never touches a hand-made
// profile. Rendering is pure: same Model + same dir ⇒ identical Targets.
func (m Model) RenderTargets(dir string) []Target {
	out := make([]Target, 0, len(m.Connections))
	for _, c := range m.Connections {
		out = append(out, Target{
			Path:    filepath.Join(dir, FileName(c.Name)),
			Content: c.render(),
		})
	}
	return out
}

// Validate rejects a model the renderer cannot compile or that would produce a
// dangerous/broken profile: an unknown connection type, a blank/duplicate name, a
// Wi-Fi profile with no SSID or a malformed country, or an IPv4 config that fails
// sanity (empty static config, unparseable address/gateway, gateway outside the
// subnet). It runs before an apply so a bad model is caught at save/apply time
// rather than after NM has been handed a profile that silently fails to load — or
// worse, one that applies and strands the node.
func (m Model) Validate() error {
	seen := map[string]bool{}
	for _, c := range m.Connections {
		if c.Name == "" {
			return fmt.Errorf("netconfig: a connection has a blank name")
		}
		if seen[c.Name] {
			return fmt.Errorf("netconfig: duplicate connection name %q", c.Name)
		}
		seen[c.Name] = true
		if c.Type != TypeEthernet && c.Type != TypeWiFi {
			return fmt.Errorf("netconfig: connection %q has unknown type %q", c.Name, c.Type)
		}
		if c.Type == TypeWiFi {
			if err := validateWiFi(c.WiFi); err != nil {
				return fmt.Errorf("netconfig: connection %q: %w", c.Name, err)
			}
		}
		if err := validateIPv4(c.IPv4); err != nil {
			return fmt.Errorf("netconfig: connection %q: %w", c.Name, err)
		}
	}
	return nil
}

// Sync makes dir's set of Waypoint-managed keyfiles match the model: it writes
// every rendered profile (atomically, 0600) and removes any stale waypoint-*
// keyfile that the model no longer contains. It NEVER touches a file that is not
// waypoint-*.nmconnection — a profile Waypoint did not create is invisible to it,
// even for deletion. Returns whether anything changed on disk (so the caller can
// skip the nmcli reload when the render is a no-op).
func (m Model) Sync(dir string) (changed bool, err error) {
	targets := m.RenderTargets(dir)
	want := make(map[string]bool, len(targets))
	for _, t := range targets {
		want[filepath.Base(t.Path)] = true
		wrote, err := writeAtomicIfChanged(t.Path, t.Content)
		if err != nil {
			return changed, err
		}
		changed = changed || wrote
	}
	// Prune managed keyfiles that dropped out of the model. Only waypoint-* files
	// are candidates — os.ReadDir surfaces everything, and managedName gates it.
	entries, err := os.ReadDir(dir)
	if err != nil {
		return changed, err
	}
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, keyfileExt) {
			continue
		}
		stem := strings.TrimSuffix(name, keyfileExt)
		if !managedName(stem) || want[name] {
			continue
		}
		if err := os.Remove(filepath.Join(dir, name)); err != nil {
			return changed, err
		}
		changed = true
	}
	return changed, nil
}

// writeAtomicIfChanged writes content to path via a temp-file+rename (a crash
// mid-write never leaves NM reading a half-written profile) at 0600, but skips the
// write when the file already holds exactly content — so an unchanged render
// leaves the mtime alone and Sync can report "no change". Returns whether it wrote.
func writeAtomicIfChanged(path, content string) (bool, error) {
	if cur, err := os.ReadFile(path); err == nil && string(cur) == content {
		return false, nil
	}
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, ".waypoint-net-*.tmp")
	if err != nil {
		return false, err
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName) // no-op after a successful rename
	if _, err := tmp.WriteString(content); err != nil {
		tmp.Close()
		return false, err
	}
	// 0600 root: system-connections files carry the Wi-Fi PSK, and NM refuses to
	// load a secret-bearing profile with looser permissions.
	if err := tmp.Chmod(0o600); err != nil {
		tmp.Close()
		return false, err
	}
	if err := tmp.Close(); err != nil {
		return false, err
	}
	return true, os.Rename(tmpName, path)
}

// sortedManagedFiles lists dir's waypoint-*.nmconnection basenames in a stable
// order. Used by the keyfile checkpoint to snapshot the managed set deterministically.
func sortedManagedFiles(dir string) ([]string, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}
	var out []string
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, keyfileExt) {
			continue
		}
		if managedName(strings.TrimSuffix(name, keyfileExt)) {
			out = append(out, name)
		}
	}
	sort.Strings(out)
	return out, nil
}
