package netconfig

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestVLANRender(t *testing.T) {
	v := VLAN{Parent: "eth0", ID: 50, Name: "iot", IPv4: IPv4{
		Method: "manual", Address: "10.50.0.2", Prefix: "24", Gateway: "10.50.0.1",
	}}
	out := v.render()
	for _, want := range []string{
		"# Generated by waypointd",
		"id=waypoint-vlan50",
		"type=vlan",
		"interface-name=eth0.50",
		"[vlan]\n",
		"parent=eth0",
		"id=50",
		"[ipv4]\n",
		"method=manual",
		"address1=10.50.0.2/24,10.50.0.1",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("VLAN keyfile missing %q\n---\n%s", want, out)
		}
	}
	// The file/profile stem is waypoint-vlan<id>.
	if FileName(v.connName()) != "waypoint-vlan50.nmconnection" {
		t.Errorf("VLAN filename = %q", FileName(v.connName()))
	}
}

// A VLAN with a DHCP block renders method=auto and no address1.
func TestVLANDHCPRender(t *testing.T) {
	v := VLAN{Parent: "eth0", ID: 100, IPv4: IPv4{Method: "auto"}}
	out := v.render()
	if !strings.Contains(out, "method=auto") || strings.Contains(out, "address1=") {
		t.Errorf("DHCP VLAN render wrong:\n%s", out)
	}
}

// VLANs fold into RenderTargets/ProfileIDs/Sync like any managed profile.
func TestVLANInSyncAndTargets(t *testing.T) {
	dir := t.TempDir()
	m := Model{VLANs: []VLAN{{Parent: "eth0", ID: 50, IPv4: IPv4{Method: "manual", Address: "10.50.0.2", Prefix: "24"}}}}
	if _, err := m.Sync(dir); err != nil {
		t.Fatalf("Sync: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "waypoint-vlan50.nmconnection")); err != nil {
		t.Errorf("vlan keyfile not written: %v", err)
	}
	ids := m.ProfileIDs()
	found := false
	for _, id := range ids {
		if id == "waypoint-vlan50" {
			found = true
		}
	}
	if !found {
		t.Errorf("ProfileIDs missing waypoint-vlan50: %v", ids)
	}
}

func TestValidateVLANs(t *testing.T) {
	cases := []struct {
		name  string
		vlans []VLAN
		ok    bool
	}{
		{"ok", []VLAN{{Parent: "eth0", ID: 50, IPv4: IPv4{Method: "auto"}}}, true},
		{"id too low", []VLAN{{Parent: "eth0", ID: 0}}, false},
		{"id too high", []VLAN{{Parent: "eth0", ID: 4095}}, false},
		{"id max ok", []VLAN{{Parent: "eth0", ID: 4094, IPv4: IPv4{Method: "auto"}}}, true},
		{"no parent", []VLAN{{Parent: "", ID: 50}}, false},
		{"dup parent+id", []VLAN{{Parent: "eth0", ID: 50, IPv4: IPv4{Method: "auto"}}, {Parent: "eth0", ID: 50, IPv4: IPv4{Method: "auto"}}}, false},
		{"same id diff parent (filename collision)", []VLAN{{Parent: "eth0", ID: 50, IPv4: IPv4{Method: "auto"}}, {Parent: "wlan0", ID: 50, IPv4: IPv4{Method: "auto"}}}, false},
		{"bad ipv4", []VLAN{{Parent: "eth0", ID: 50, IPv4: IPv4{Method: "manual"}}}, false},
	}
	for _, tc := range cases {
		err := validateVLANs(tc.vlans)
		if tc.ok && err != nil {
			t.Errorf("%s: unexpected error %v", tc.name, err)
		}
		if !tc.ok && err == nil {
			t.Errorf("%s: expected an error", tc.name)
		}
	}
}

func TestValidateHost(t *testing.T) {
	cases := []struct {
		name string
		h    Host
		ok   bool
	}{
		{"blank ok", Host{}, true},
		{"simple", Host{Hostname: "wpsd"}, true},
		{"fqdn", Host{Hostname: "node.lan.example"}, true},
		{"digits+hyphen", Host{Hostname: "wp-01"}, true},
		{"leading hyphen", Host{Hostname: "-bad"}, false},
		{"trailing hyphen", Host{Hostname: "bad-"}, false},
		{"space", Host{Hostname: "has space"}, false},
		{"underscore", Host{Hostname: "under_score"}, false},
		{"empty label", Host{Hostname: "a..b"}, false},
	}
	for _, tc := range cases {
		err := validateHost(tc.h)
		if tc.ok && err != nil {
			t.Errorf("%s: unexpected error %v", tc.name, err)
		}
		if !tc.ok && err == nil {
			t.Errorf("%s: expected an error", tc.name)
		}
	}
}
